# Generated by Django 4.1.7 on 2023-02-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisite.user'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisite.user'),
        ),
        migrations.AlterField(
            model_name='righttouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisite.user'),
        ),
    ]
