# Generated by Django 4.1.7 on 2023-02-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0002_user_alter_comment_user_alter_novel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='users', to='apisite.user'),
        ),
    ]
