# Generated by Django 4.1.7 on 2023-02-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0003_novel_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='favorite_num',
            field=models.IntegerField(default=0),
        ),
    ]
