# Generated by Django 4.1.7 on 2023-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0005_alter_novel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_introduction',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
