# Generated by Django 4.1.7 on 2023-02-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0006_user_self_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
