# Generated by Django 4.1.7 on 2023-02-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0007_comment_content_alter_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='read_later',
            field=models.ManyToManyField(blank=True, related_name='users_read_later', to='apisite.user'),
        ),
    ]
