# Generated by Django 4.1.7 on 2023-02-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0008_novel_read_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.ManyToManyField(blank=True, related_name='follow', to='apisite.user'),
        ),
    ]
