# Generated by Django 4.1.7 on 2023-02-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0009_user_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='relationship',
            new_name='follow',
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower', to='apisite.user'),
        ),
    ]
