# Generated by Django 4.1.7 on 2023-02-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0010_rename_relationship_user_follow_user_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
    ]
